EVALUATE
VAR StartTs = DATE(__YEAR__, __MONTH__, __DAY__) + TIME(__HOUR__, __MINUTE__, __SECOND__)
VAR EndTs = StartTs + TIME(0, 0, 1)
RETURN
SELECTCOLUMNS(
    FILTER(
        'Kusto Query Result',
        'Kusto Query Result'[cameraId] = __CAMERA_ID__
            && 'Kusto Query Result'[receivedAtUtc] >= StartTs
            && 'Kusto Query Result'[receivedAtUtc] < EndTs
            && NOT ISBLANK('Kusto Query Result'[ChunkBase64])
    ),
    "ChunkIndex", 'Kusto Query Result'[ChunkIndex]
)
ORDER BY [ChunkIndex] ASC
